### PR TITLE
Add standalone1604 build

### PR DESCRIPTION
**Pull request by giorgiosironi**
* ~depends on https://github.com/elifesciences/bot-lax-adaptor/pull/530~ merged
* ~depends on https://github.com/elifesciences/builder-base-formula/pull/208~ merged

### CODE REVIEW

**Comment by giorgiosironi** [comment]
16.04 failed as expected. Also `base` failed, which is not great.

**Comment by lsh-0** [comment]
the old 16.04 changes have been merged in after running the gauntlet, updating this branch with the new master

**Comment by lsh-0** [comment]
> Also base failed, which is not great.

I do believe I've merged your builder-base changes as well as mine since this comment, fingers crossed this build goes better

**Comment by lsh-0** [comment]
single state failing, nginx:
```
[18.212.77.111] out: ----------
[18.212.77.111] out:           ID: nginx-server-service
[18.212.77.111] out:     Function: service.running
[18.212.77.111] out:         Name: nginx
[18.212.77.111] out:       Result: False
[18.212.77.111] out:      Comment: Running scope as unit run-r8bd29c6aeac6448f93a55edeab349a3b.scope.
[18.212.77.111] out:               Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
[18.212.77.111] out:      Started: 04:05:41.873514
[18.212.77.111] out:     Duration: 105.553 ms
[18.212.77.111] out:      Changes:   
[18.212.77.111] out: ----------
```

not happening locally, but I'll try a build from scratch

**Comment by lsh-0** [comment]
can't replicate nginx failure locally

**Comment by lsh-0** [comment]
giving build a kick

**Comment by lsh-0** [comment]
just waiting on the bot-lax PR to be merged before this build will go green

**Comment by lsh-0** [comment]
glencoe issue is resolved, kicking build

**Comment by lsh-0** [comment]
(sent this as an email, sorry @giorgiosironi , force of habit?) 

the weird error is here:

> [2019-03-20T04:15:01.898Z] ssh: Could not resolve hostname ci--lax.elife.internal: Name or service not known

I tried stopping and starting the `lax--ci` instance, thinking the DNS records 'somehow' got lost in the churn. No luck.

Turns out the lax config has "intdomain: False" , which happened 18+ months ago:
https://github.com/elifesciences/builder/commit/c49161614b3ec677b2cab00c7f79f5b777ff332c

I don't know where that snippet of script lives - any ideas?

**Comment by lsh-0** [comment]
christ, wrong ticket again. I'm getting dizzy from all these github issues

**Comment by lsh-0** [comment]
not sure if it belongs here, but this formula update is blocked by the bot-lax update for lax which is in turned blocked by a failure in the pipeline here: https://alfred.elifesciences.org/job/dependencies-lax-update-bot-lax-adaptor/

lax pins bot-lax which is pinned at a version that doesn't have python3.6 support

**Comment by lsh-0** [comment]
16.04 has a problem with `black` because it requires python 3.6 and only has 3.5 is available. Using Black for scrubbing shouldn't be a breaking change nor  preclude us from a particular OS. I've opened a PR for lax here: https://github.com/elifesciences/lax/pull/439

18.04 has systemd service/socket problems:

```
[2019-05-08T07:08:41.800Z] [50.19.158.2] out: ----------
[2019-05-08T07:08:41.800Z] [50.19.158.2] out:           ID: uwsgi-lax.socket
[2019-05-08T07:08:41.800Z] [50.19.158.2] out:     Function: service.running
[2019-05-08T07:08:41.800Z] [50.19.158.2] out:       Result: False
[2019-05-08T07:08:41.800Z] [50.19.158.2] out:      Comment: The named service uwsgi-lax.socket is not available
[2019-05-08T07:08:41.800Z] [50.19.158.2] out:      Started: 07:02:47.878643
[2019-05-08T07:08:41.800Z] [50.19.158.2] out:     Duration: 61.262 ms
[2019-05-08T07:08:41.800Z] [50.19.158.2] out:      Changes:   
[2019-05-08T07:08:41.800Z] [50.19.158.2] out: ----------
[2019-05-08T07:08:41.800Z] [50.19.158.2] out:           ID: uwsgi-lax
[2019-05-08T07:08:41.800Z] [50.19.158.2] out:     Function: service.running
[2019-05-08T07:08:41.800Z] [50.19.158.2] out:       Result: False
[2019-05-08T07:08:41.800Z] [50.19.158.2] out:      Comment: Failed to start uwsgi-lax.service: Unit uwsgi-lax.service not found.
[2019-05-08T07:08:41.800Z] [50.19.158.2] out:      Started: 07:02:48.022773
[2019-05-08T07:08:41.800Z] [50.19.158.2] out:     Duration: 386.891 ms
[2019-05-08T07:08:41.800Z] [50.19.158.2] out:      Changes:   
[2019-05-08T07:08:41.800Z] [50.19.158.2] out: ----------
```

**Comment by lsh-0** [comment]
it's completing without issue on 18.04 on vagrant. kicking build, recreating vagrant instance

**Comment by lsh-0** [comment]
> 18.04 has systemd service/socket problems:

reverse requisites were not all there. builds fine on vagrant 18.04 from scratch

**Comment by lsh-0** [comment]
PR: https://github.com/elifesciences/builder-configuration/pull/65

it's missing the service definitions.

**Comment by lsh-0** [comment]
PR: https://github.com/elifesciences/builder-configuration/compare/lax-1804-multiservice?expand=1

**Comment by lsh-0** [comment]
long time coming. goodbye branch, you were almost a year old

**Pull request merged**
