### PR TITLE
Enables New Relic monitoring on Lax HTTP requests

### PR DESCRIPTION
**Pull request by giorgiosironi**
To correctly instrument Django applications, we need to run the `uwsgi` command inside a wrapper provided by the New Relic Python library.

In order to do this sanely, the daemonization of Lax is also ported from `daemon` to Upstart.

This depends on https://github.com/elifesciences/lax/pull/27

Hopefully if this is useful I would try to port some of these states into builder-base formula for ease of use from other Python projects.

How does it look like?
General feeling of web transactions:
screenshot from 2016-10-18 17 20 20
Impact of transactions on server load and their performance, categorized by controller:
screenshot from 2016-10-18 17 21 06
Database operations measurements to understand what is the bottleneck:
screenshot from 2016-10-18 17 21 49

### CODE REVIEW

**Comment by lsh-0** [comment]
ah, you went ahead and wrote the upstart script, thanks! it was on my todo list for today.

**Comment by giorgiosironi** [comment]
Incidentally `daemon` wouldn't run with the Python `newrelic-admin` wrapper because of its too broad permissions; also restart wasn't working as we saw in production.

**Comment by lsh-0** [comment]
yes, the `daemon` tool is a pita. it sometimes work, often doesn't, the rules for making it work are arcane. I'm removing it whenever I find it. I add the `no-more-daemon` state to a project's formula when it's free

**Comment by lsh-0** [comment]
ok, I've tidied it up a bit. killing the daemon processes is handled in the `no-more-daemon` state so I removed that from the lax formula. I'm also leaving the remove init script to a once-off command I'll run over the lax instances.

**Comment by giorgiosironi** [comment]
Have to merge https://github.com/elifesciences/lax/pull/27 or this will crash upon the next deployment

**Comment by lsh-0** [comment]
done

**Pull request merged**
