### PR TITLE
Use elife.newrelic-python

### PR DESCRIPTION
**Pull request by giorgiosironi**
All projects now outsource this to builder-base-formula

### CODE REVIEW

**Comment by lsh-0** [comment]
you didn't up builder-private `salt/top.sls` file to remove `lax.newrelic`.

**Comment by lsh-0** [comment]
fixed, but now it's back to me to figure out what the rds permission thing is complaining about

**Comment by giorgiosironi** [comment]
Ah right, sorry about that. I remember adding the new state but not removing the old one.

**Comment by lsh-0** [comment]
all good

**Pull request merged**
