### PR TITLE
rds db is now created and owned by the root db user, rds_superuser

### PR DESCRIPTION
**Pull request by lsh-0**
app user is granted all privileges on this database.

this has been copied from the observer formula which is only known to work locally and hasn't been tested on remotely yet

### CODE REVIEW

**Comment by giorgiosironi** [comment]
When testing this on a new instance, I would try to run the test suite as it sometimes touches the database to reset its state. It has to still be able to clean the data between tests.

**Comment by lsh-0** [comment]
changes are very similar to those in observer.

**Comment by giorgiosironi** [comment]
Failure is a non-deterministic startup of uwsgi-bot-lax-adaptor:
```
[54.82.169.48] out:           ID: uwsgi-bot-lax-adaptor
[54.82.169.48] out:     Function: cmd.run
[54.82.169.48] out:         Name: curl --silent --include --head --fail https://lax-formula-pr-10--lax.elifesciences.org:8001/ui/
[54.82.169.48] out:       Result: False
[54.82.169.48] out:      Comment: Command "curl --silent --include --head --fail https://lax-formula-pr-10--lax.elifesciences.org:8001/ui/" run
[54.82.169.48] out:      Started: 06:08:14.621740
[54.82.169.48] out:     Duration: 26.756 ms
[54.82.169.48] out:      Changes:   
[54.82.169.48] out:               ----------
[54.82.169.48] out:               pid:
[54.82.169.48] out:                   22377
[54.82.169.48] out:               retcode:
[54.82.169.48] out:                   7
[54.82.169.48] out:               stderr:
[54.82.169.48] out:               stdout:
```
If this is a race condition, we have a script that may help: https://github.com/elifesciences/iiif-formula/blob/master/salt/iiif/loris.sls#L235 but I've seen a similar problem due to `newrelic.ini` being created too late in the process, that could be another reason. On a second highstate both these problems solve themselves, but we need to make them work on the first.

**Comment by lsh-0** [comment]
> but we need to make them work on the first.

absolutely. I've been bitten by this specific bug before as well. I'll see if I can't make it a bit more robust today or, at the very least, emit an error or something to work with

**Pull request merged**
