### PR TITLE
bot-lax, turns off pre-validation of article-json in the api

### PR DESCRIPTION
**Pull request by lsh-0**
this means lax does all the validation with it's proper error messages

### CODE REVIEW

**Comment by lsh-0** [comment]
bot-lax smoke test failed. it honestly looked like a salt bug so I'm giving it another kick and hopefully I can acquire a lock before it gets torn down

**Comment by lsh-0** [comment]
I can replicate it on a masterless instance, investigating

**Comment by lsh-0** [comment]
taking a stab in the dark with `init_delay`. I suspect it might be the restart that comes immediately after it, but we'll see

**Comment by giorgiosironi** [comment]
> I can replicate it on a masterless instance, investigating.

The best way I have to replicate formula builds is also to copy the `masterless.launch` command from the build and create a separate instance with another name like `lax--pr-29-manual`.

**Comment by lsh-0** [comment]
That's good to know. I thought I was supposed to acquire a lock but that got frustrating quickly.

**Comment by lsh-0** [comment]
I think it might actually be nginx?? I can see `listener_nginx-server-service` restarting nginx at the same time the check is happening

```
[34.226.202.113] out: ----------
[34.226.202.113] out:           ID: uwsgi-bot-lax-adaptor
[34.226.202.113] out:     Function: cmd.run
[34.226.202.113] out:         Name: restart uwsgi-bot-lax-adaptor
[34.226.202.113] out:       Result: True
[34.226.202.113] out:      Comment: Command "restart uwsgi-bot-lax-adaptor" run
[34.226.202.113] out:      Started: 07:58:27.760390
[34.226.202.113] out:     Duration: 5028.023 ms
[34.226.202.113] out:      Changes:   
[34.226.202.113] out:               ----------
[34.226.202.113] out:               pid:
[34.226.202.113] out:                   23742
[34.226.202.113] out:               retcode:
[34.226.202.113] out:                   0
[34.226.202.113] out:               stderr:
[34.226.202.113] out:               stdout:
[34.226.202.113] out:                   uwsgi-bot-lax-adaptor start/running, process 23747
[34.226.202.113] out: ----------
[34.226.202.113] out:           ID: uwsgi-bot-lax-smoke-test
[34.226.202.113] out:     Function: http.wait_for_successful_query
[34.226.202.113] out:         Name: https://pr-29-base-update--lax.elifesciences.org:8001/ui/
[34.226.202.113] out:       Result: False
[34.226.202.113] out:      Comment: An exception occurred in this state: Traceback (most recent call last):
[34.226.202.113] out:                 File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1870, in call
[34.226.202.113] out:                   **cdata['kwargs'])
[34.226.202.113] out:                 File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1818, in wrapper
[34.226.202.113] out:                   return f(*args, **kwargs)
[34.226.202.113] out:                 File "/usr/lib/python2.7/disERROR - buildercore.core - sudo() received nonzero return code 2 while executing!        Requested: /bin/bash /tmp/highstate.sh-20180718075256    Executed: sudo -S -p 'sudo password:'  /bin/bash -l -c "/bin/bash /tmp/highstate.sh-20180718075256"

t-packages/salt/states/http.py", line 163, in wait_for_successful_query
[34.226.202.113] out:                   raise caught_exception  # pylint: disable=E0702
[34.226.202.113] out:               error: [Errno 111] Connection refused
[34.226.202.113] out:      Started: 07:58:32.790413
[34.226.202.113] out:     Duration: 10040.744 ms
[34.226.202.113] out:      Changes:   
[34.226.202.113] out: ----------
[34.226.202.113] out:           ID: listener_nginx-server-service
[34.226.202.113] out:     Function: service.mod_watch
[34.226.202.113] out:         Name: nginx
[34.226.202.113] out:       Result: True
[34.226.202.113] out:      Comment: Service restarted
[34.226.202.113] out:      Started: 07:58:42.832179
[34.226.202.113] out:     Duration: 1086.422 ms
[34.226.202.113] out:      Changes:   
[34.226.202.113] out:               ----------
[34.226.202.113] out:               nginx:
[34.226.202.113] out:                   True
[34.226.202.113] out: ----------
[34.226.202.113] out:           ID: listener_uwsgi-lax
[34.226.202.113] out:     Function: service.mod_watch
[34.226.202.113] out:         Name: uwsgi-lax
[34.226.202.113] out:       Result: True
[34.226.202.113] out:      Comment: Service reloaded
[34.226.202.113] out:      Started: 07:58:43.918979
[34.226.202.113] out:     Duration: 24.592 ms
[34.226.202.113] out:      Changes:   
[34.226.202.113] out:               ----------
[34.226.202.113] out:               uwsgi-lax:
[34.226.202.113] out:                   True
```

**Comment by lsh-0** [comment]
ay ya ya ya

justshootme

I knew I shouldn't have re-enabled that smoke test, even though everything was passing.

**Pull request merged**
