### PR TITLE
Use the extracted nginx macro

### PR DESCRIPTION
**Pull request by giorgiosironi**
Depends on https://github.com/elifesciences/builder-base-formula/pull/194

### CODE REVIEW

**Comment by giorgiosironi** [comment]
`base` fails:
```
[34.207.208.66] out:           ID: ejp-lax-adaptor
[34.207.208.66] out:     Function: cmd.run
[34.207.208.66] out:         Name: ./install.sh
[34.207.208.66] out:       Result: False
[34.207.208.66] out:      Comment: Command "./install.sh" run
[34.207.208.66] out:      Started: 14:30:22.784628
[34.207.208.66] out:     Duration: 4193.062 ms
[34.207.208.66] out:      Changes:   
[34.207.208.66] out:               ----------
[34.207.208.66] out:               pid:
[34.207.208.66] out:                   19940
[34.207.208.66] out:               retcode:
[34.207.208.66] out:                   1
[34.207.208.66] out:               stderr:
[34.207.208.66] out:                   Command "hg clone --noupdate -q ssh://hg@bitbucket.org/lskibinski/scraper /tmp/pip-install-4WMByS/scraper" failed with error code 255 in None
[34.207.208.66] out:               stdout:
...
[34.207.208.66] out:                   Collecting scraper from hg+ssh://hg@bitbucket.org/lskibinski/scraper#egg=scraper (from -r requirements.txt (line 2))
[34.207.208.66] out:                     Cloning hg ssh://hg@bitbucket.org/lskibinski/scraper to /tmp/pip-install-4WMByS/scraper
[34.207.208.66] out:                   abort: no suitable response from remote hg!
[34.207.208.66] out: ----------
```

**Comment by giorgiosironi** [comment]
The project page says it has been superseded by `et3`, can it be replace in `ejp-lax-adaptor`?

**Comment by lsh-0** [comment]
grr - this is turning out to be a pita.

I'll double check the certificate issue again and maybe, possibly, hopefully, something has updated and that machine can use https again, but if not I'll get ejp-adaptor working today and unblock you

**Comment by lsh-0** [comment]
ejp-lax-adaptor has been updated, I'll kick this build now

**Comment by lsh-0** [comment]
two failures, this one:

```
[35.172.192.181] out: ----------
[35.172.192.181] out:           ID: lax-nginx-conf
[35.172.192.181] out:     Function: file.managed
[35.172.192.181] out:         Name: /etc/nginx/sites-enabled/lax.conf
[35.172.192.181] out:       Result: False
[35.172.192.181] out:      Comment: Unable to manage file: Jinja error: elife/nginx-macros.sls
[35.172.192.181] out:               Traceback (most recent call last):
[35.172.192.181] out:                 File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 418, in render_jinja_tmpl
[35.172.192.181] out:                   output = template.render(**decoded_context)
[35.172.192.181] out:                 File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
[35.172.192.181] out:                   return self.environment.handle_exception(exc_info, True)
[35.172.192.181] out:                 File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
[35.172.192.181] out:                   reraise(exc_type, exc_value, tb)
[35.172.192.181] out:                 File "<template>", line 18, in top-level template code
[35.172.192.181] out:                 File "/usr/lib/python2.7/dist-packages/salt/utils/jinja.py", line 136, in get_source
[35.172.192.181] out:                   raise TemplateNotFound(template)
[35.172.192.181] out:               TemplateNotFound: elife/nginx-macros.sls
[35.172.192.181] out:               
[35.172.192.181] out:               ; line 18
[35.172.192.181] out:               
[35.172.192.181] out:               ---
[35.172.192.181] out:               [...]
[35.172.192.181] out:                   server_name "";
[35.172.192.181] out:                   return 444;
[35.172.192.181] out:               }
[35.172.192.181] out:               {% endif %}
[35.172.192.181] out:               
[35.172.192.181] out:               {% from 'elife/nginx-macros.sls' import consumer_groups_filter %}    <======================
[35.172.192.181] out:               {{ consumer_groups_filter(pillar.lax.app.users) }}
[35.172.192.181] out:               
[35.172.192.181] out:               # configuration of the server
[35.172.192.181] out:               server {
[35.172.192.181] out:                   # we always listen on port 80.
[35.172.192.181] out:               [...]
[35.172.192.181] out:               ---
[35.172.192.181] out:      Started: 18:17:54.374816
[35.172.192.181] out:     Duration: 23.472 ms
[35.172.192.181] out:      Changes:   
[35.172.192.181] out: ----------
```

and the other cascades from it.

**Comment by lsh-0** [comment]
which is weird because I can see it's been merged in: 
https://github.com/elifesciences/builder-base-formula/pull/194/files

**Comment by giorgiosironi** [comment]
Perhaps you clicked on a previous build, following `continuous-integration/jenkins/pr-fresh` leads to:
```
[18.215.149.241] out:           ID: ejp-lax-adaptor
[18.215.149.241] out:     Function: cmd.run
[18.215.149.241] out:         Name: ./install.sh
[18.215.149.241] out:       Result: False
[18.215.149.241] out:      Comment: Command "./install.sh" run
[18.215.149.241] out:      Started: 02:50:13.209378
[18.215.149.241] out:     Duration: 85.935 ms
[18.215.149.241] out:      Changes:   
[18.215.149.241] out:               ----------
[18.215.149.241] out:               pid:
[18.215.149.241] out:                   19741
[18.215.149.241] out:               retcode:
[18.215.149.241] out:                   1
[18.215.149.241] out:               stderr:
[18.215.149.241] out:                   /usr/bin/python: No module named venv
[18.215.149.241] out:               stdout:
```

**Comment by giorgiosironi** [comment]
Yes, `pr-update` has a link to an old build because the new build won't get to it until `pr-base` is green (first need to build the `master` formula before the change can be applied to it).

**Comment by giorgiosironi** [comment]
(not a blocker by the way, `journal-cms-formula` can go its own way without this which is reuse of extracted code)

**Comment by lsh-0** [comment]
> /usr/bin/python: No module named venv

I think this must be a Ubuntu vs Arch thing. `python` on my machine points to python3, I bet on Ubuntu 16.04 it points to python2, so `python -m venv` would naturally fail. I'll fix this up today.

**Comment by lsh-0** [comment]
ejp is fixed up now and I've kicked the build again. I usually go into the last of the failures and click the 'rerun' button and that almost always works. I used pr-fresh this time to restart the build instead of pr-head.

**Comment by giorgiosironi** [comment]
>  I used pr-fresh this time to restart the build 

For reference, it shouldn't matter what you use to _restart_ the build as it's a monolithic build anyway and everything will be eventually re-executed.

**Pull request merged**
